# To pass all tests you need >=20 orders with the state "confirmed" (bestätigt)
username: '' # Your Billbee Username
password: '' # Your Billbee API Password
api_key:  '' # Your Billbee API Key
sample_product: '' # A existing product (Id) with an valid SKU
shop_id: '' # A existing shop (Id)
tag: '' # A order tag which is set at over 20 orders
sample_order: '' # A existing order (Id)
sample_order_number: '' # A existing order (External Reference)
partner_id: '' # A order id from a external system
partner: '' # The partner name of the external system. Take a look in Partner-Class
custom_field_definition_id: '' # The id of a custom field definition
web_hook_uri: '' # The uri for testing webhooks
test_delete_web_hooks: false # If true, the delete all web hooks call will be tested